#version: '3.8'
#services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    environment:
#      POSTGRES_DB: jwt_users
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 12345
#    ports:
#      - "5436:5434"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    command: postgres -c 'port=5434'
#
#
#  app:
#    image: my-spring-boot-app:latest
##    build:
##      context: .
##      dockerfile: Dockerfile
#    container_name: spring-app
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5434/jwt_users
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 12345
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
##      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
#      SPRING_JPA_SHOW_SQL: "true"
#      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
#      SPRING_JPA_DATABASE: postgresql
#      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
#
#volumes:
#  postgres-data:
