
GET http://localhost:8080/api/demo

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "adil.alimbaev.04@gmail.com",
  "password": "12346"
}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "login": "adil1",
  "email": "adil.alimbaev.04@gmail.com",
  "password": "12346"
}
###
POST http://localhost:8080/api/auth/check
Content-Type: application/json

{
  "code": "2283"
}